language: crystal
script:
- bash bin/deps
- bash bin/spec
- bash bin/docs
deploy:
- provider: pages
  github-token: $GH_TOKEN
  local-dir: docs
  target-branch: gh-pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
