language: crystal
cache:
  directories:
  - $HOME/miniconda
  - $HOME/.cache/Tectonic
  - report/pyg
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda -u;
    conda config --add channels conda-forge;
    conda config --set always_yes yes;
  fi
- conda update -n base conda
- if ! command -v pygmentize > /dev/null; then conda install pygments; fi
- if ! command -v tectonic > /dev/null; then conda install tectonic; fi
- conda update --all
script:
- bash bin/deps
- bash bin/spec
- bash bin/docs
- bash bin/report
deploy:
- provider: pages
  github-token: $GH_TOKEN
  local-dir: report/out
  target-branch: report
  skip-cleanup: true
  keep-history: false
  on:
    branch: master
- provider: pages
  github-token: $GH_TOKEN
  local-dir: docs
  target-branch: gh-pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
