language: c
compiler:
- gcc
- clang
matrix:
  fast_finish: true
install:
- |
    wget https://nim-lang.org/download/nim-0.17.2.tar.xz
    tar -xf nim-0.17.2.tar.xz
    cd nim-0.17.2
    sh build.sh
    cd ..
before_script:
- set -e
- set -x
- export PATH=`pwd`/nim-0.17.0/bin:$PATH
script:
- nimble install -y
- nim c --cc:$CC --verbosity:0 hibari
# - nim doc --docSeeSrcUrl:https://github.com/wopian/hibari-api/blob/master --project hibari
