language: crystal
cache:
  directories:
  - $HOME/miniconda
  - $HOME/.cache/Tectonic
  - report/pyg
jobs:
  include:
    - script: bin/travis_crystal
    - script: bin/travis_latex
    - stage: deploy crystal docs
      script: skip
      deploy:
        provider: pages
        github-token: $GH_TOKEN
        local-dir: docs
        target-branch: gh-pages
        skip-cleanup: true
        keep-history: true
        on:
          branch: master
    - stage: deploy latex report
      script: skip
      deploy:
        provider: pages
        github-token: $GH_TOKEN
        local-dir: report/out
        target-branch: report
        skip-cleanup: true
        keep-history: false
        on:
          branch: master
