language: c
env:
- NIMVERSION=0.17.2
compiler:
- gcc
- clang
matrix:
  fast_finish: true
install:
- |
    wget https://nim-lang.org/download/nim-$NIMVERSION.tar.xz
    tar -xf nim-$NIMVERSION.tar.xz
    cd nim-$NIMVERSION
    sh build.sh
    ./bin/nim c koch
    ./koch boot -d:release
    ./koch nimble
    cd ..
before_script: export PATH=$HOME/nim-$NIMVERSION/bin:$PATH
script:
- nimble install -y
- nim c --cc:$CC --verbosity:0 hibari
# - nim doc --docSeeSrcUrl:https://github.com/wopian/hibari-api/blob/master --project hibari
