language: crystal
cache:
  directories:
  - $HOME/miniconda
before_install: ./db/seed.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda -u;
    conda config --add channels conda-forge;
    conda config --set always_yes yes;
    conda update --all;
    conda install tectonic;
  fi
- conda info -a
before_script: crystal deps
script:
- crystal spec
- crystal docs
- tectonic report/index.tex --outdir report/out --synctex --chatter minimal #-shell-escape
deploy:
- provider: pages
  github-token: $GH_TOKEN
  local-dir: report/out
  target-branch: report
  skip-cleanup: true
  keep-history: false
  on:
    branch: master
- provider: pages
  github-token: $GH_TOKEN
  local-dir: docs
  target-branch: gh-pages
  skip-cleanup: true
  keep-history: false
  on:
    branch: master
